# Generated by Django 5.0 on 2023-12-19 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_category_alter_recipe_cover_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='Category',
            new_name='category',
        ),
    ]
